### ISSUE TITLE
popchams

### ISSUE THREAD

**Issue by yeli1337** [xiguajerry/ashhack#1]
当popchams开启时autocrystal渲染失效 holeesp渲染失效 `packetmine渲染失效

**Comment by moeyinlo** [comment]
原版有没有这个bug

**Comment by yeli1337** [comment]
> 原版有没有这个bug

原版有popchams吗:)

**Comment by moeyinlo** [comment]
现在没有添加任何功能，你可以看一下仓库里那个jar
